# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Player'),
        ),
    ]
